name: app
description: "A new Flutter project."

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  dev_tools:
    path: ../dev_tools


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  